#!/bin/sh

HEALTH_HOST=${HEALTH_HOST}
#HEALTH_HOST=10.13.13.1

sed -i 's/10.0.0.0\/8/10.0.0.0\/24/g' /config/wg0.conf

for run in {0..10}
do
#        nc -zv -w10 $SERVERIP $SERVERPORT && break
         ping -c 1 $HEALTH_HOST >/dev/null
done
if [ $? -ne 0 ]
then
   RESULT=1
   echo "healthcheck ERROR"
   exit 1
else
   RESULT=0
   echo "healthcheck OK"
   exit 0
fi
