#!/bin/sh

SERVICE="$1"
SERVERIP=10.13.13.1



for run in {0..15}
do
#        nc -zv -w10 $SERVERIP $SERVERPORT && break
         ping -c 1 $SERVERIP
done
if [ $? -ne 0 ]
then
   RESULT=1
   echo "healthcheck ERROR"
   exit 1
else
   RESULT=0
   echo "healthcheck OK"
   exit 0
fi
